import {
  Profile,
  InfrastructureAsset,
  ActivityLog,
  SecurityAlert,
  ApiKey,
} from './supabase';

export const demoProfiles: Profile[] = [
  {
    id: 'user-admin-1',
    email: 'admin@urban.city',
    full_name: 'Alex Carter',
    role: 'admin',
    department: 'City Security Operations',
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-eng-1',
    email: 'engineer@urban.city',
    full_name: 'Priya Singh',
    role: 'city_engineer',
    department: 'Infrastructure Engineering',
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-maint-1',
    email: 'maintenance@urban.city',
    full_name: 'James Miller',
    role: 'maintenance_staff',
    department: 'Field Maintenance',
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-public-1',
    email: 'viewer@urban.city',
    full_name: 'Public Viewer',
    role: 'public_viewer',
    department: null,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoInfrastructureAssets: InfrastructureAsset[] = [
  {
    id: 'asset-bridge-1',
    name: 'Downtown River Bridge',
    type: 'bridge',
    location: { lat: 37.779, lng: -122.42 },
    status: 'operational',
    health_score: 94,
    last_inspection: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    maintenance_due: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30).toISOString(),
    description: 'Primary arterial bridge connecting downtown and west district.',
    metadata: { span: '480m', built_year: 1998 },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 365).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'asset-road-1',
    name: 'Central Expressway',
    type: 'road',
    location: { lat: 37.768, lng: -122.45 },
    status: 'maintenance_required',
    health_score: 78,
    last_inspection: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
    maintenance_due: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10).toISOString(),
    description: 'High-traffic corridor with scheduled resurfacing.',
    metadata: { lanes: 6, avg_daily_traffic: 120000 },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 200).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'asset-light-1',
    name: 'Harbor District Streetlights',
    type: 'streetlight',
    location: { lat: 37.804, lng: -122.41 },
    status: 'critical',
    health_score: 42,
    last_inspection: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    maintenance_due: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
    description: 'Cluster outage reported affecting 12 blocks near the harbor.',
    metadata: { affected_lights: 37 },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'asset-water-1',
    name: 'Northside Water Main',
    type: 'water_pipeline',
    location: { lat: 37.79, lng: -122.43 },
    status: 'operational',
    health_score: 88,
    last_inspection: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    maintenance_due: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60).toISOString(),
    description: 'Primary water supply line for northern residential districts.',
    metadata: { diameter_mm: 900 },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 300).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'asset-hospital-1',
    name: 'Metro General Hospital',
    type: 'hospital',
    location: { lat: 37.765, lng: -122.42 },
    status: 'maintenance_required',
    health_score: 81,
    last_inspection: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    maintenance_due: new Date(Date.now() + 1000 * 60 * 60 * 24 * 15).toISOString(),
    description: 'Critical care facility with backup power and network links.',
    metadata: { beds: 550 },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 400).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoActivityLogs: ActivityLog[] = [
  {
    id: 'log-1',
    user_id: 'user-admin-1',
    action: 'login_success',
    resource: 'auth',
    details: {},
    ip_address: '10.0.0.21',
    status: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'log-2',
    user_id: 'user-eng-1',
    action: 'update_asset',
    resource: 'infrastructure_assets.asset-bridge-1',
    details: { field: 'health_score', old: 88, new: 94 },
    ip_address: '10.0.0.42',
    status: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'log-3',
    user_id: 'user-maint-1',
    action: 'create_report',
    resource: 'maintenance_reports.asset-light-1',
    details: { type: 'emergency', priority: 'urgent' },
    ip_address: '10.0.1.17',
    status: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
  },
  {
    id: 'log-4',
    user_id: 'user-admin-1',
    action: 'api_key_created',
    resource: 'api_keys.key-admin-dashboard',
    details: { rate_limit: 1000 },
    ip_address: '10.0.0.21',
    status: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
  },
  {
    id: 'log-5',
    user_id: 'user-eng-1',
    action: 'view_security_alerts',
    resource: 'security_alerts',
    details: {},
    ip_address: '10.0.0.42',
    status: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
  },
];

export const demoSecurityAlerts: SecurityAlert[] = [
  {
    id: 'alert-1',
    alert_type: 'brute_force',
    severity: 'high',
    user_id: 'user-admin-1',
    description: 'Multiple failed login attempts detected from external IP 34.221.10.5.',
    details: { attempts: 23, window_minutes: 10 },
    ip_address: '34.221.10.5',
    resolved: false,
    resolved_at: null,
    resolved_by: null,
    created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: 'alert-2',
    alert_type: 'api_abuse',
    severity: 'medium',
    user_id: 'user-eng-1',
    description: 'Unusual spike in API traffic from key `urban_mobile_prod`.',
    details: { requests_per_minute: 2300 },
    ip_address: '192.168.10.8',
    resolved: true,
    resolved_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    resolved_by: 'user-admin-1',
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'alert-3',
    alert_type: 'unauthorized_access',
    severity: 'critical',
    user_id: null,
    description: 'Blocked access to restricted maintenance API from unknown client.',
    details: { path: '/v1/maintenance/emergency', method: 'POST' },
    ip_address: '185.23.71.9',
    resolved: false,
    resolved_at: null,
    resolved_by: null,
    created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: 'alert-4',
    alert_type: 'suspicious_activity',
    severity: 'low',
    user_id: 'user-public-1',
    description: 'Public viewer account accessed outside usual geolocation.',
    details: { previous_country: 'US', new_country: 'CA' },
    ip_address: '142.250.72.3',
    resolved: true,
    resolved_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    resolved_by: 'user-admin-1',
    created_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
];

export const demoApiKeys: ApiKey[] = [
  {
    id: 'key-1',
    key: 'urban_admin_dashboard_XXXXXXXXXXXXXXXX',
    name: 'Admin Dashboard',
    created_by: 'user-admin-1',
    permissions: ['read', 'write', 'manage'],
    rate_limit: 1000,
    is_active: true,
    last_used: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    expires_at: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
  },
  {
    id: 'key-2',
    key: 'urban_mobile_public_YYYYYYYYYYYYYYYYYYYY',
    name: 'Mobile Public Viewer',
    created_by: 'user-admin-1',
    permissions: ['read'],
    rate_limit: 500,
    is_active: true,
    last_used: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    expires_at: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(),
  },
  {
    id: 'key-3',
    key: 'urban_third_party_ZZZZZZZZZZZZZZZZZZZZ',
    name: '3rd-Party Analytics',
    created_by: 'user-admin-1',
    permissions: ['read'],
    rate_limit: 200,
    is_active: false,
    last_used: null,
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
];


